auth:
    mode: headless
default:
    active-within: 24h0m0s
    autoclose: true
    autoclose-timeout: "10"
    group: "11111111111111111111111111111111"
    log-level: ""
    identity-provider: ""
    org-name: ""
    skip-auto-login: false
    skip-version-check: false
    social-login: email
    use-refresh-token: true
output:
    color:
        fail: ""
        pass: ""
        warn: ""
        info: ""
        highlight: ""
        secondary: ""
        special: ""
    silent: false
platform:
    api: https://console-api.enforce.dev
    audience: https://console-api.enforce.dev
    console: https://console.chainguard.dev
    issuer: https://issuer.enforce.dev
    registry: https://cgr.dev
